### ISSUE TITLE
got error while getMediaDetails method. when include library in another project, can you help me?

### ISSUE THREAD

**Issue by kashifansari786** [brarcher/video-transcoder#172]
2020-07-28 19:56:39.852 451-1588/com.video.videos E/FFmpeg: Exception while trying to run: [/data/user/0/com.video.videos/files/ffprobe, -i, /storage/emulated/0/Movies/Video-send-intent-file.tmp, -v, quiet, -print_format, json, -show_streams, -show_format]
    java.io.IOException: Cannot run program "/data/user/0/com.video.videos/files/ffprobe": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:698)
        at java.lang.Runtime.exec(Runtime.java:563)
        at nl.bravobit.ffmpeg.ShellCommand.run(ShellCommand.java:11)
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:40)
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:11)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:698) 
        at java.lang.Runtime.exec(Runtime.java:563) 
        at nl.bravobit.ffmpeg.ShellCommand.run(ShellCommand.java:11) 
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:40) 
        at nl.bravobit.ffmpeg.FFcommandExecuteAsyncTask.doInBackground(FFcommandExecuteAsyncTask.java:11) 
        at android.os.AsyncTask$3.call(AsyncTask.java:378) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by brarcher** [comment]
Interesting. What happens is the app will extract the ffprobe program somewhere so it can execute it:

https://github.com/bravobit/FFmpeg-Android/blob/master/android-ffmpeg/src/main/java/nl/bravobit/ffmpeg/FFprobe.java#L65

It seems that it either extracted it somewhere different than were it expected, or it failed to do it entirely. 

Do you have logcat logs from when the app starts up and a file is loaded? That would help point out what is going on.

As a side note, I'll probably not be able to dig in and help much with the issue. I'm mostly on [hiatus](https://github.com/brarcher/video-transcoder#note-from-developer) from the project. There may be someone from the community who could provide some insight.
